import type { ScreeningQuestion } from './types.ts';

const q = (
  id: string,
  band: 'A' | 'B' | 'C',
  targetGrade: string,
  difficulty: 'Easy' | 'Medium' | 'Challenging',
  teachingJudgment: boolean,
  correctAnswer: 'A' | 'B' | 'C' | 'D',
  promptEN: string,
  promptZH: string,
  options: Array<[string, string]>
): ScreeningQuestion => ({
  id,
  band,
  targetGrade,
  difficulty,
  teachingJudgment,
  correctAnswer,
  prompt: { EN: promptEN, ZH: promptZH },
  options: Object.fromEntries(
    options.map(([EN, ZH], index) => [String.fromCharCode(65 + index), { EN, ZH }])
  ) as ScreeningQuestion['options']
});

export const TEST_VERSION = 'Teacher Math Screening v1.0';

export const SCREENING_QUESTIONS: ScreeningQuestion[] = [
  q('Q01', 'A', 'G1', 'Easy', false, 'B',
    'Teacher Sarah has 1 box of 10 pencils and 7 loose pencils. If she receives 5 more loose pencils, how many full boxes of 10 and loose pencils will she have in total?',
    'Sarah 老师有 1 盒铅笔，每盒 10 支，另外还有 7 支散装铅笔。如果她又收到 5 支散装铅笔，那么现在一共有几整盒铅笔和几支散装铅笔？',
    [['1 box and 12 loose pencils', '1 盒和 12 支散装铅笔'], ['2 boxes and 2 loose pencils', '2 盒和 2 支散装铅笔'], ['2 boxes and 5 loose pencils', '2 盒和 5 支散装铅笔'], ['3 boxes and 0 loose pencils', '3 盒和 0 支散装铅笔']]),
  q('Q02', 'A', 'G1', 'Medium', true, 'B',
    'A Grade 1 student is given: 8 + 2 = □ + 4. The student writes 10 in the box. Which explanation would best help the student understand the mistake?',
    '一名一年级学生遇到下面这道题：8 + 2 = □ + 4。学生在方框里填了 10。下面哪种解释最能帮助学生真正理解自己的错误？',
    [['Tell the student that 8 + 2 = 10, so they must subtract 4 from 10 to get 6.', '告诉学生 8 + 2 = 10，所以再用 10 - 4，就能得到 6。'], ['Show the student a balance scale and explain that both sides of the equal sign must have the same total value.', '用天平模型向学生解释，等号左右两边的总数值必须相等。'], ['Remind the student that the box is always the answer to the addition on the left.', '提醒学生，方框永远应该填写等号左边算式计算出的答案。'], ['Give the student a calculator to check the answer.', '让学生使用计算器检查答案。']]),
  q('Q03', 'A', 'G2', 'Medium', true, 'A',
    'Leo has 12 stickers. Maya has 5 more stickers than Leo. A student subtracts and answers that Maya has 7 stickers. How can a teacher best help this student?',
    'Leo 有 12 张贴纸。Maya 比 Leo 多 5 张贴纸。一名学生使用减法，回答 Maya 有 7 张贴纸。老师采用哪种方法最能帮助学生理解这道题？',
    [['Draw two lines of blocks: one with 12 blocks for Leo and a longer line with 5 additional blocks for Maya.', '画两排方块：一排用 12 个方块表示 Leo，另一排在相同的 12 个方块基础上再增加 5 个方块表示 Maya。'], ['Tell the student to memorize that the word "more" always means addition.', '让学生记住，只要看到“多”就一定使用加法。'], ['Explain only that 7 is smaller than 12, so it cannot be correct.', '只告诉学生 7 比 12 小，所以答案不可能正确。'], ['Have the student rewrite the word problem three times.', '让学生把题目重新抄写三遍。']]),
  q('Q04', 'A', 'G3', 'Medium', false, 'B',
    'A baker makes 36 cookies and puts them into boxes of 4 cookies each. Each box is sold for $5. How much money will the baker collect if all the boxes are sold?',
    '一名面包师制作了 36 块饼干，每 4 块装成一盒。每盒售价 5 美元。如果所有饼干都卖完，一共可以获得多少钱？',
    [['$32', '32 美元'], ['$45', '45 美元'], ['$80', '80 美元'], ['$144', '144 美元']]),
  q('Q05', 'A', 'G3', 'Medium', true, 'B',
    'A student says: "1/5 is larger than 1/3 because 5 is larger than 3." Which explanation would best help the student understand the mistake?',
    '一名学生说：“1/5 比 1/3 大，因为 5 比 3 大。”下面哪种解释最能帮助学生理解自己的错误？',
    [['Tell the student to memorize that a larger denominator always means a smaller fraction.', '让学生记住：分母越大，分数就一定越小。'], ['Draw two same-size pizzas, divide one into 3 equal slices and the other into 5 equal slices, and compare one slice from each pizza.', '画两个同样大小的披萨，一个平均分成 3 份，另一个平均分成 5 份，然后比较两个披萨中的其中一份。'], ['Convert both fractions to decimals using a calculator.', '使用计算器把两个分数转换成小数进行比较。'], ['Tell the student that fractions always work in the opposite way from whole numbers.', '告诉学生，分数的规律永远和整数相反。']]),
  q('Q06', 'A', 'G3', 'Challenging', false, 'C',
    'A rectangular garden has an area of 40 square meters. Its length is 8 meters. What is the perimeter of the garden?',
    '一个长方形花园的面积是 40 平方米，长是 8 米。这个花园的周长是多少？',
    [['5 meters', '5 米'], ['13 meters', '13 米'], ['26 meters', '26 米'], ['32 meters', '32 米']]),
  q('Q07', 'B', 'G4', 'Medium', false, 'B',
    'A winter jacket costs $80, which is 4 times as much as a sweater. How much do the jacket and the sweater cost together?',
    '一件冬季夹克售价 80 美元，是一件毛衣价格的 4 倍。夹克和毛衣一共多少钱？',
    [['$20', '20 美元'], ['$100', '100 美元'], ['$320', '320 美元'], ['$400', '400 美元']]),
  q('Q08', 'B', 'G4', 'Medium', true, 'B',
    'A teacher wants to show Grade 4 students why 2/3 is equivalent to 4/6. Which visual method would be clearest?',
    '一名老师想向四年级学生解释为什么 2/3 和 4/6 相等。下面哪种视觉方法最清楚？',
    [['Write (2 × 2)/(3 × 2) = 4/6 and tell students to multiply the top and bottom by the same number.', '在黑板上写出 (2 × 2)/(3 × 2) = 4/6，然后告诉学生分子和分母同时乘以相同的数。'], ['Draw a rectangle divided into 3 equal parts with 2 parts shaded, then split each of the 3 parts in half to show 4 shaded parts out of 6 equal parts.', '画一个平均分成 3 份的长方形并涂其中 2 份，然后把原来的每一份再平均分成两份，让学生看到涂色部分变成了 6 份中的 4 份。'], ['Convert both fractions to percentages.', '把两个分数都转换成百分数。'], ['Write the numbers 2, 3, 4, and 6 in a table.', '把数字 2、3、4、6 写进一个表格。']]),
  q('Q09', 'B', 'G4', 'Medium', false, 'C',
    'A school bus can safely seat up to 45 students. How many buses are needed to transport 200 students?',
    '一辆校车最多可以安全乘坐 45 名学生。要运送 200 名学生，至少需要多少辆校车？',
    [['4', '4 辆'], ['4 buses with 20 students left over', '4 辆，另外剩下 20 名学生'], ['5', '5 辆'], ['6', '6 辆']]),
  q('Q10', 'B', 'G5', 'Medium', false, 'B',
    'Sarah has 2 cups of flour. She uses 1/2 cup to bake a cake and 1/3 cup to make cookies. How much flour does she have left?',
    'Sarah 原来有 2 杯面粉。她做蛋糕用了 1/2 杯，做饼干又用了 1/3 杯。她还剩多少面粉？',
    [['1/6 cup', '1/6 杯'], ['1 1/6 cups', '1 又 1/6 杯'], ['1 1/5 cups', '1 又 1/5 杯'], ['1 5/6 cups', '1 又 5/6 杯']]),
  q('Q11', 'B', 'G5', 'Medium', true, 'B',
    'A student says: "Multiplying two numbers always gives a result larger than both numbers." Which example best shows that this statement is not always true?',
    '一名学生说：“两个数相乘，结果一定比原来的两个数都大。”下面哪个例子最能说明这个说法并不总是正确？',
    [['8 × 1 = 8', '8 × 1 = 8'], ['8 × 1/2 = 4', '8 × 1/2 = 4'], ['8 × 2 = 16', '8 × 2 = 16'], ['8 × 1.5 = 12', '8 × 1.5 = 12']]),
  q('Q12', 'B', 'G6', 'Medium', false, 'C',
    'A winter coat regularly costs $120 and is on sale for 25% off. What is the sale price before tax?',
    '一件冬季外套原价 120 美元，现在打 75 折，也就是优惠 25%。税前折后价是多少？',
    [['$30', '30 美元'], ['$85', '85 美元'], ['$90', '90 美元'], ['$95', '95 美元']]),
  q('Q13', 'B', 'G6', 'Challenging', false, 'B',
    'Five students scored 80, 85, 90, 90, and 95 on a test. Their mean score is 88. A sixth student scores 70. What happens to the mean score of the group?',
    '5 名学生的考试成绩分别是 80、85、90、90 和 95，平均分是 88。第 6 名学生考了 70 分。加入这名学生的成绩后，整个小组的平均分会发生什么变化？',
    [['The mean increases.', '平均分上升'], ['The mean decreases.', '平均分下降'], ['The mean stays the same.', '平均分不变'], ['The mean becomes 70.', '平均分变成 70']]),
  q('Q14', 'C', 'G7', 'Medium', false, 'B',
    'A store increases the wholesale price of a toaster by 20%. If the retail price is $60, what was the original wholesale price?',
    '一家商店在烤面包机的批发价基础上加价 20% 后出售。如果零售价是 60 美元，那么原来的批发价是多少？',
    [['$48', '48 美元'], ['$50', '50 美元'], ['$52', '52 美元'], ['$72', '72 美元']]),
  q('Q15', 'C', 'G7', 'Medium', false, 'B',
    'Solve for x: 3(x - 4) + 5 = 14',
    '求 x：3(x - 4) + 5 = 14',
    [['x = 3', 'x = 3'], ['x = 7', 'x = 7'], ['x = 9', 'x = 9'], ['x = 11', 'x = 11']]),
  q('Q16', 'C', 'G7', 'Medium', true, 'A',
    'A student expands 4(x + 3) as 4x + 3. Which visual explanation would best help the student understand why the correct expression is 4x + 12?',
    '一名学生把 4(x + 3) 展开成 4x + 3。下面哪种视觉解释最能帮助学生理解为什么正确结果应该是 4x + 12？',
    [['Draw a rectangle with height 4 and width (x + 3), then split it into two rectangles with areas 4x and 12.', '画一个高为 4、宽为 (x + 3) 的长方形，再把它分成两个小长方形，它们的面积分别是 4x 和 12。'], ['Tell the student to memorize: "Multiply the outside number by everything inside."', '让学生背规则：“括号外面的数要乘括号里面所有的数。”'], ['Substitute x = 0 and ask the student to compare the two expressions.', '令 x = 0，让学生比较两个表达式。'], ['Tell the student to add 4 and 3 before working with x.', '告诉学生应该先把 4 和 3 相加，再处理 x。']]),
  q('Q17', 'C', 'G8', 'Medium', false, 'B',
    'A water tank contains 800 gallons of water and drains at a constant rate of 25 gallons per minute. Which equation represents the amount of water W remaining after t minutes?',
    '一个水箱里原有 800 加仑水，并以每分钟 25 加仑的恒定速度排水。经过 t 分钟后，水箱中剩余水量 W 可以用哪个方程表示？',
    [['W = 800 + 25t', 'W = 800 + 25t'], ['W = 800 - 25t', 'W = 800 - 25t'], ['W = 25t - 800', 'W = 25t - 800'], ['W = 800 / (25t)', 'W = 800 / (25t)']]),
  q('Q18', 'C', 'G8', 'Medium', false, 'B',
    'What is the slope of the line passing through the points (1, 3) and (4, 11)?',
    '一条直线经过点 (1, 3) 和 (4, 11)。这条直线的斜率是多少？',
    [['3/8', '3/8'], ['8/3', '8/3'], ['3', '3'], ['8', '8']]),
  q('Q19', 'C', 'G8', 'Challenging', false, 'B',
    'At a bookstore, 2 notebooks and 3 pens cost $11, while 2 notebooks and 5 pens cost $15. All notebooks have the same price, and all pens have the same price. What is the cost of one notebook?',
    '在一家书店，2 本笔记本和 3 支笔一共 11 美元，2 本相同的笔记本和 5 支相同的笔一共 15 美元。每本笔记本价格相同，每支笔价格也相同。一本笔记本多少钱？',
    [['$2.00', '2.00 美元'], ['$2.50', '2.50 美元'], ['$3.00', '3.00 美元'], ['$4.00', '4.00 美元']]),
  q('Q20', 'C', 'G9', 'Challenging', false, 'B',
    'A rectangle has a length that is 3 meters longer than its width. The area of the rectangle is 40 square meters. What is its perimeter?',
    '一个长方形的长比宽多 3 米。它的面积是 40 平方米。这个长方形的周长是多少？',
    [['13 meters', '13 米'], ['26 meters', '26 米'], ['28 meters', '28 米'], ['40 meters', '40 米']])
];
